Resources:
    TransitGateway:
        Type: AWS::EC2::TransitGateway
        Properties:
            DefaultRouteTableAssociation: "enable"
            Description: "Transit Gateway"
            DnsSupport: "enable"
            Tags: 
                - Key: Name
                - Value: Transit Gateway

    DevTransitGatewayAttachment:
        Type: AWS::EC2::TransitGatewayAttachment
        Properties: 
            SubnetIds: 
                - Fn::ImportValue: Dev-Private-Subnet-1
                - Fn::ImportValue: Dev-Private-Subnet-2
            Tags: 
                - Key: Name
                - Value: Dev-TGW-Attachment
            TransitGatewayId: !Ref TransitGateway
            VpcId: Fn::ImportValue: Dev-VPC
    EgressTransitGatewayAttachment:
            Type: AWS::EC2::TransitGatewayAttachment
            Properties: 
                SubnetIds: 
                    - Fn::ImportValue: Egress-Private-Subnet-1
                    - Fn::ImportValue: Egress-Private-Subnet-2
                Tags: 
                    - Key: Name
                    - Value: Egress-TGW-Attachment
                TransitGatewayId: !Ref TransitGateway
                VpcId: Fn::ImportValue: Egress-VPC

Outputs:
    TransitGateway:
        Description: A reference to the Transit Gateway
        Value: !Ref TransitGateway
        Export:
                Name: Transit-Gateway
    TransitGatewayAttachment:
        Description: A reference to the Transit Gateway Attachment
        Value: !Ref DevTransitGatewayAttachment
        Export:
                Name: Dev-Transit-Gateway-Attachment
    TransitGatewayAttachment:
        Description: A reference to the Transit Gateway Attachment
        Value: !Ref EgressTransitGatewayAttachment
        Export:
                Name: Egress-Transit-Gateway-Attachment